<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <Description>A .NET Generic Host Builder for running CS2 Dedicated Servers.</Description>
    <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
    <OptimizationPreference>Speed</OptimizationPreference>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <None Include="$(SourceDirectory)..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNet.Security.OpenId.Steam" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="$(AspNetCoreVersion)" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.Common" Version="10.6.0" />
    <PackageReference Include="Racoon.Extensions.CounterStrike" Version="1.1.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\App\CS2Launcher.AspNetCore.App.csproj" />
  </ItemGroup>

</Project>
