name: default

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main
  workflow_dispatch:

env:
  DOTNET_NOLOGO: true
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          cache: true
          cache-dependency-path: ./**/packages.lock.json
          dotnet-version: |
            8.0.x
            9.0.x

      - name: restore
        run: dotnet workload restore && dotnet restore --locked-mode

      - name: build
        run: dotnet build --no-restore

  pack:
    needs: [build]
    if: startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/heads/develop')

    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: true

      - name: setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          cache: true
          cache-dependency-path: ./**/packages.lock.json
          dotnet-version: |
            8.0.x
            9.0.x

      - name: restore
        run: dotnet workload restore && dotnet workload install wasm-tools-net8 && dotnet restore --locked-mode

      - name: pack
        run: dotnet pack -c Release -o dist --no-restore

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cs2-launcher-packages
          path: dist

  publish:
    needs: [pack]

    runs-on: windows-latest
    steps:
      - name: setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: cs2-launcher-packages

      - name: push
        run: dotnet nuget push "*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
